# Generated by Django 3.2.6 on 2022-03-18 15:44

from django.db import migrations


def create_admin_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.create_superuser(username='admin', password='testpassword')
    
def revert_changes(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin_user, revert_changes)
    ]
