# Generated by Django 3.2.6 on 2022-03-18 15:41

from django.db import migrations, models
import django_geofield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('position', django_geofield.fields.GeoPositionField(db_index=True, max_length=32)),
            ],
        ),
    ]
